### ISSUE TITLE
cusolver error: 7, when calling `cusolverDnCreate(handle)`

### ISSUE THREAD

**Issue by looooog0421** [cliport/cliport#39]
when I run
```
python cliport/eval.py model_task=multi-language-conditioned \
                       eval_task=stack-block-pyramid-seq-seen-colors \
                       agent=cliport \
                       mode=test \
                       n_demos=10 \
                       train_demos=1000 \
                       exp_folder=cliport_quickstart \
                       checkpoint_type=test_best \
                       update_results=True \
                       disp=True
```
meet the bug:
```
Save path for results: /home/lgx/Project/cliport/cliport_quickstart/stack-block-pyramid-seq-seen-colors-cliport-n1000-train/checkpoints/
int args: [ven = NVIDIA Corporation
steps=400000-val_loss=0.00014655.ckpt
Evaluating: ['steps=400000-val_loss=0.00014655.ckpt']
ven = NVIDIA Corporation
Attn FCN - Stream One: plain_resnet_lat, Stream Two: clip_lingunet_lat, Stream Fusion: add
Transport FCN - Stream One: plain_resnet_lat, Stream Two: clip_lingunet_lat, Stream Fusion: conv
Agent: stack-block-pyramid-seq-seen-colors-cliport-n10, Logging: False
Loaded: /home/lgx/Project/cliport/cliport_quickstart/multi-language-conditioned-cliport-n1000-train/checkpoints/steps=400000-val_loss=0.00014655.ckpt
Test: 1/10
Traceback (most recent call last):
  File "cliport/eval.py", line 132, in main
    act = agent.act(obs, info, goal)
  File "/home/lgx/Project/cliport/cliport/agents/transporter_lang_goal.py", line 82, in act
    pick_conf = self.attn_forward(pick_inp)
  File "/home/lgx/Project/cliport/cliport/agents/transporter_lang_goal.py", line 43, in attn_forward
    out = self.attention.forward(inp_img, lang_goal, softmax=softmax)
  File "/home/lgx/Project/cliport/cliport/models/streams/two_stream_attention_lang_fusion.py", line 47, in forward
    in_tens = self.rotator(in_tens, pivot=pv)
  File "/home/lgx/Project/cliport/cliport/utils/utils.py", line 595, in __call__
    x_warped: torch.tensor = kornia.warp_affine(x.float(), M.to(x.device), dsize=(h, w))
  File "/home/lgx/anaconda3/envs/cliport_env/lib/python3.8/site-packages/kornia/geometry/transform/imgwarp.py", line 143, in warp_affine
    dst_norm_trans_src_norm: torch.Tensor = normalize_homography(
  File "/home/lgx/anaconda3/envs/cliport_env/lib/python3.8/site-packages/kornia/geometry/warp/homography_warper.py", line 350, in normalize_homography
    src_pix_trans_src_norm = torch.inverse(src_norm_trans_src_pix)
RuntimeError: cusolver error: 7, when calling `cusolverDnCreate(handle)`

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2024-03-13 12:22:59,280][wandb.sdk.internal.internal][INFO] - Internal process exited
```
My environment:
```
Nvidia 4060ti & Driver Version: 550.54.14
cuda: 11.0
```

What should I do?
Look forward to your reply!

**Comment by MohitShridhar** [comment]
From a quick google, it looks like you are running out of GPU memory?
https://github.com/rapidsai/cuml/issues/183

**Comment by MohitShridhar** [comment]
Closing due to inactivity/

**Comment by AkagawaTsurunaki** [comment]
Edit file `cliport/utils/utils.py` at line 595.
```python
# Comment line 595
# x_warped: torch.tensor = kornia.warp_affine(x.float(), M.to(x.device), dsize=(h, w))
x_warped: torch.tensor = kornia.warp_affine(x.float().to("cpu"), M.to("cpu"), dsize=(h, w))
x_warped = x_warped.to(x.device)
```
This is not a perfect solution because I move the tensor from CUDA device to CPU device, but it just works.
