### ISSUE TITLE
ValueError: 'a' cannot be empty unless no samples are taken

### ISSUE THREAD

**Issue by qingweihk** [cliport/cliport#5]
Hi,thanks for your great job.

I try to train and got the following error:

Traceback (most recent call last):
  File "/home/adminis/qw/My_Projects/cliport_env/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/adminis/qw/My_Projects/cliport_env/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/home/adminis/qw/My_Projects/cliport_env/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/home/adminis/qw/My_Projects/cliport_env/lib/python3.8/site-packages/hydra/core/utils.py", line 128, in run_job
    ret.return_value = task_function(task_cfg)
  File "cliport/train.py", line 69, in main
    val_ds = RavensDataset(os.path.join(data_dir, '{}-val'.format(task)), cfg, n_demos=n_val, augment=False)
  File "/home/adminis/qw/My_Projects/cliport/cliport/dataset.py", line 60, in __init__
    episodes = np.random.choice(range(self.n_episodes), self.n_demos, False)
  File "mtrand.pyx", line 773, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cliport/train.py", line 78, in <module>
    main()
  File "/home/adminis/qw/My_Projects/cliport_env/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/home/adminis/qw/My_Projects/cliport_env/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/home/adminis/qw/My_Projects/cliport_env/lib/python3.8/site-packages/hydra/_internal/utils.py", line 237, in run_and_report
    assert mdl is not None
AssertionError
[2021-11-26 18:16:01,603][wandb.sdk.internal.internal][INFO] - Internal process exited

**Comment by MohitShridhar** [comment]
@qingweihk this probably means there weren't enough demonstrations for training. If you set  `n_demos=1000` for train.py, you should have generated at least 1000 demos or more with the [demos.py](https://github.com/cliport/cliport#single-task) script prior training.

I'll see if I can add an exception handle for this.

**Comment by MohitShridhar** [comment]
Added an exception in https://github.com/cliport/cliport/commit/202f96e36eb247759bbec0840d4af2cb75a4e1a1
